### ISSUE TITLE
autocompletion search in blog not working properly

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-lang#701] opened 2017-07-17 10:11 UTC
up and down arrow is not selecting the previous/next item

![out](https://user-images.githubusercontent.com/921490/28263885-e3461d2c-6ae8-11e7-9cc9-3c56462a916c.gif)

**Comment by heathermiller** [comment] 2017-07-17 10:14
Ooh, good catch! Thanks :)

**Comment by marnux** [comment] 2018-07-18 16:49
The issue is situated in the Simple Jekyll Search plugin. Which is out of scope for the scala spree.
Either this needs to be fixed in the plugin or another plugin needs to be chosen with this functionality.
I made a pull request to pull in the latest version of the plugin, it at least prevents the result container from being cleared when pushing the arrow keys.

**Comment by SethTisue** [comment] 2018-07-20 00:35
verified that that the PR makes the improvement described, at least. thank you!

**Closed by SethTisue** 2018-07-20 00:35 UTC
Labels: bug, good first issue

**Comment by jvican** [comment] 2018-07-22 08:34
Would it make sense to remove this Jekyll search and use instead the new algolia search that we use in docs?
