### ISSUE TITLE
Should Travis fail on Jekyll warnings?

### ISSUE THREAD

**Issue by ashawley** [scala/scala-lang#607] opened 2017-02-27 18:46 UTC
Jekyll warning thrown in the build for #606:

    Build Warning: Layout 'blog' requested in blog/_posts/2017-02-27-scalafix-v0.3.md does not exist.

Not sure the cause, or if the consequence is severe (I think the blog post gets deleted, but again not sure...) but was wondering if this was something that should be caught by Travis.

Jekyll errors was last taken up in #537

**Comment by SethTisue** [comment] 2017-02-28 03:48
> but was wondering if this was something that should be caught by Travis

it certainly seems to me that it should!

**Comment by dominv** [comment] 2017-02-28 12:18
For what I know so far, Jekyll is currently only throwing fatal errors but it doesn't consider the inability to process a file a fatal error so it shows a warning and it finishes the build exiting with 0.

This specific warning is caused by a recent post file not located in its new custom collection. It will be fixed on an upcoming commit.

**Closed** 2017-03-07 18:42 UTC
