### ISSUE TITLE
Some historical links are dead

### ISSUE THREAD

**Issue by DarkDimius** [scala/scala-lang#655] opened 2017-05-30 14:23 UTC
E.g. 2.11 release nodes link from https://news.ycombinator.com/item?id=7621622 is dead

**Comment by SethTisue** [comment] 2018-02-15 23:21
@Philippus should we close this now?

**Comment by SethTisue** [comment] 2018-03-21 15:20
we have automated link checking now, as part of PR validation.

**Closed by SethTisue** 2018-03-21 15:20 UTC

**Comment by Philippus** [comment] 2018-03-21 19:20
I think the issue is about incoming links that used to work, like for example the one mentioned on ycombinator. We could add redirects for links that change or are removed, but that would require a lot of effort I think.

**Comment by SethTisue** [comment] 2018-03-21 21:14
Ohhh... was skimming tickets too fast. But I’m tempted to leave it closed since so much time has passed since the big site overhaul
