### ISSUE TITLE
Many type hierarchy diagrams no longer available

### ISSUE THREAD

**Issue by Lasering** [scala/scala-lang#551] opened 2016-11-22 11:58 UTC
For example:
In Scala 2.11.7 the type hierarchy diagram existed for `Option`:
http://www.scala-lang.org/api/2.11.6/index.html#scala.Option
But in [Scala 2.11.8](http://www.scala-lang.org/api/2.11.8/index.html#scala.Option) and [Scala 2.12.0](http://www.scala-lang.org/api/current/scala/Option.html) it vanished.

The same happened for every `AnyVal` subtype, eg: `Int`, `Long`, `Double`, etc.
It also happened for immutable.{Set, List, Map}.

PS: I hope I'm opening an issue in the right project.

**Comment by SethTisue** [comment] 2016-11-22 19:10
duplicate of https://github.com/scala/scala-dev/issues/105 (but yes this was the right place for you to report this, there's no way you could have known to go hunting over in scala-dev; thank you for reporting)

The problem shows up on scala-lang.org, but I think the place we'll need to fix it is probably https://github.com/scala/scala-jenkins-infra

**Closed by SethTisue** 2016-11-22 19:10 UTC
Labels: bug
