### ISSUE TITLE
code sections hard to read for some readers (thin font, low contrast)

### ISSUE THREAD

**Issue by lrytz** [scala/scala-lang#445] opened 2016-07-12 15:34 UTC
https://twitter.com/mraleph/status/752888195398955008 for an example

**Comment by lrytz** [comment] 2016-07-12 15:35
here's a copy of the screenshot:

![cnllziuw8aadyby](https://cloud.githubusercontent.com/assets/119636/16773137/fc978e7e-4856-11e6-8c80-60dca6521a63.jpg)

**Comment by soc** [comment] 2016-07-23 08:20
@lrytz I was also annoyed by it. The issue is that there are 5 different fonts `Monaco,Menlo,Consolas,"Courier New",monospace` given in the CSS, which makes it hard to be sure that a fix really did it on all the various OSes and devices.
I replaced it with a single font, Roboto Mono (10.5px, weight 400) which fixed this issue for me. Maybe that helps!

**Comment by SethTisue** [comment] 2016-10-18 17:02
one fix attempt was https://github.com/scala/scala-lang/pull/467, but it lost syntax highlighting

**Comment by SethTisue** [comment] 2016-11-08 18:04
fixed by #510

**Closed by SethTisue** 2016-11-08 18:04 UTC
Labels: bug
