### ISSUE TITLE
Make evergreen URL for SLS current version

### ISSUE THREAD

**Issue by mslinn** [scala/scala-lang#1066] opened 2019-08-08 23:25 UTC
I propose that this URL:
https://www.scala-lang.org/files/archive/spec/current
always resolve to the SLS version corresponding to the current version of Scala.
At present one must know the correct URL, which makes it harder to find for those new to Scala.

**Comment by SethTisue** [comment] 2019-08-15 15:39
duplicate of #584

**Closed by SethTisue** 2019-08-15 15:39 UTC
